config/routes.rb
Rails.application.routes.draw do
  get '/new' => 'citations#new'
  post '/new' => 'citations#create'
  resources :citations

  root "citations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
class Citation < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController

  def index
    @citations = Citation.all
  end

  def new
  	@citation = Citation.new
  end

  def create
  	@citation = Citation.new(citation_params)

    @citation.save
    redirect_to root_path
  end

  private
    def citation_params
      params.require(:citation).permit(:citation_text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/views/citations/index.html.haml
%h1 List of citations:
%ul
  - @citations.each do |t|
    %li
      = t.citation_text
%div.btn-toolbar
  %div.btn-group-horizontal
    %p= link_to('Add new citation', new_citation_path)

app/views/citations/new.html.haml
%h1 Add new citation
=form_for @citation do |t|
  %div
    = t.label :citation_text
    = t.text_field :citation_text
    = t.submit "Create"
%div.btn-toolbar
  %div.btn-group-horizontal
    %p= link_to('Back', root_path)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Citations
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield